### ISSUE TITLE
Exception when watcher triggers

### ISSUE THREAD

**Issue by jakepearson** [liebke/zookeeper-clj#10]
Hi,
I am trying to listen to changes to the children of a node in zookeeper.  I have 2 REPLs running.  One to create a leaf node and one to listen for the watcher callback.  The watcher REPL dumps out a stacktrace when I save a child node in the writer REPL.

```
user=> (defn group-watcher [^String group-name]
  #_=>   (let [group (zk/children client group-name :watcher group-watcher :watch? true)]
  #_=>     (prn "Group members: " group)))
#'user/group-watcher
user=> (group-watcher "/services/foo")
"Group members: " ("jake2" "jake")
nil
user=> 2013-09-16 15:39:09,583 [nREPL-worker-0-EventThread] ERROR org.apache.zookeeper.ClientCnxn  - Error while calling watcher
java.lang.IllegalArgumentException: No matching method found: getChildren for class org.apache.zookeeper.ZooKeeper
  at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:80)
  at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
  at zookeeper$children.doInvoke(zookeeper.clj:230)
  at clojure.lang.RestFn.invoke(RestFn.java:521)
  at user$group_watcher.invoke(form-init5604638546801990357.clj:2)
  at zookeeper.internal$make_watcher$reify__839.process(internal.clj:56)
  at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:526)
  at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:502)
```

Here is the line that writes out the data:

```
 (zookeeper/create @client "/services/foo/jake2 :data (data/to-bytes "http://jake2:123"))
```

Please let me know if you have any ideas or if I can supply more information.

thanks,
Jake

**Comment by kazuhiro** [comment]
I couldn't replicate this issue. Is it still valid in terms of current version of zookeeper-clj?
